# Generated by Django 6.1 on 2026-08-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('trekking', 'Trekking'), ('tour', 'Tour'), ('sightseeing', 'Sightseeing'), ('climbing', 'Climbing')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='trips/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
